"""
Multi-language support — English, German, Russian, Polish.
Add more languages by extending the STRINGS dict.
"""
from __future__ import annotations

LANGUAGES: dict[str, str] = {
    "en": "English",
    "de": "Deutsch",
    "ru": "Русский",
    "pl": "Polski",
}

STRINGS: dict[str, dict[str, str]] = {
    "en": {
        # Buttons
        "btn.back_menu": "⬅ Menu",
        "btn.back": "⬅ Back",
        "btn.refresh": "🔄 Refresh",
        "btn.next": "▶ Next",
        "btn.prev": "◀ Prev",
        # Menu
        "menu.welcome": "👋 Welcome! Choose an option:",
        "menu.title": "📋 Main Menu",
        "menu.status": "📊 Status",
        "menu.temps": "🌡 Temps",
        "menu.files": "📁 Files",
        "menu.control": "🎮 Control",
        "menu.gcode": "⌨ GCode",
        "menu.macros": "🔧 Macros",
        "menu.camera": "📷 Camera",
        "menu.system": "💻 System",
        "menu.estop": "🚨 E-Stop",
        "menu.settings": "⚙ Settings",
        "menu.adjust": "🎛 Adjust",
        "menu.history": "📜 History",
        "menu.bed_mesh": "🗺 Bed Mesh",
        "menu.printers": "🖨 Printers",
        # Status
        "status.title": "📊 Printer Status",
        "status.offline": "❌ Printer offline or unreachable.",
        "status.file": "File",
        "status.state": "State",
        "status.progress": "Progress",
        "status.hotend": "Hotend",
        "status.bed": "Bed",
        "status.fan": "Fan",
        "status.speed": "Speed",
        "status.print_time": "Print time",
        "status.total_time": "Total time",
        "status.snapshot": "📷 Snapshot",
        "status.auto_on": "⏸ Auto-off",
        "status.auto_off": "▶ Auto-on",
        # Temps
        "temps.title": "🌡 Temperature Control",
        "temps.custom": "Custom",
        "temps.cool_all": "❄ Cool All",
        "temps.set_hotend": "Hotend → {val}°C",
        "temps.set_bed": "Bed → {val}°C",
        "temps.cooled": "Cooling down...",
        "temps.enter_hotend": "Enter hotend temperature (°C):",
        "temps.enter_bed": "Enter bed temperature (°C):",
        # Files
        "files.title": "📁 Files",
        "files.files": "files",
        "files.page": "page",
        "files.sort": "Sort",
        "files.size": "Size",
        "files.filament": "Filament",
        "files.time": "Est. time",
        "files.layer": "Layer height",
        "files.slicer": "Slicer",
        "files.print": "🖨 Print",
        "files.delete": "🗑 Delete",
        "files.print_confirm": "Print {name}?",
        "files.print_yes": "✅ Yes, print",
        "files.print_no": "❌ Cancel",
        "files.print_started": "✅ Printing: {name}",
        "files.print_failed": "❌ Failed to start: {name}",
        "files.delete_confirm": "Delete {name}?",
        "files.delete_yes": "✅ Yes, delete",
        "files.delete_no": "❌ Cancel",
        "files.deleted": "🗑 Deleted: {name}",
        "files.delete_failed": "❌ Delete failed: {name}",
        # Control
        "control.title": "🎮 Print Control",
        "control.pause": "⏸ Pause",
        "control.resume": "▶ Resume",
        "control.cancel": "⏹ Cancel",
        "control.home": "🏠 Home",
        "control.motors_off": "💤 Motors Off",
        "control.cancel_confirm": "⚠ Cancel the current print?",
        "control.cancel_yes": "✅ Yes, cancel",
        "control.cancel_no": "❌ No",
        "control.paused": "Print paused.",
        "control.resumed": "Print resumed.",
        "control.cancelled": "Print cancelled.",
        "control.homed": "Homed.",
        "control.motors_off_done": "Motors off.",
        # GCode
        "gcode.title": "⌨ GCode Console\n\nSend a command or pick a quick button:",
        # Macros
        "macros.title": "🔧 Macros",
        "macros.found": "found",
        "macros.confirm": "Run macro: {name}?",
        "macros.run_yes": "✅ Run",
        "macros.run_no": "❌ Cancel",
        "macros.ran": "✅ Ran: {name}",
        "macros.failed": "❌ Failed: {name}",
        # Camera
        "camera.title": "📷 Camera",
        "camera.snapshot": "📸 Snapshot",
        "camera.stream": "📺 Live Stream",
        "camera.fetching": "Fetching snapshot...",
        "camera.caption": "📸 Snapshot",
        "camera.error": "❌ Could not fetch snapshot.",
        # System
        "system.title": "💻 System Info",
        "system.klipper": "Klipper",
        "system.moonraker": "Moonraker",
        "system.cpu": "CPU",
        "system.disk": "Disk",
        "system.cpu_usage": "CPU usage",
        "system.mem": "Memory",
        "system.uptime": "Uptime",
        "system.fw_restart": "🔄 FW Restart",
        "system.host_restart": "🔌 Host Restart",
        "system.confirm": "⚠ Confirm: {action}?",
        "system.confirm_yes": "✅ Yes",
        "system.confirm_no": "❌ No",
        "system.fw_restarted": "✅ Firmware restarted.",
        "system.host_restarted": "✅ Host restart initiated.",
        # E-Stop
        "estop.confirm": "🚨 EMERGENCY STOP — are you sure?",
        "estop.confirm_yes": "🚨 YES, STOP",
        "estop.confirm_no": "❌ Cancel",
        "estop.executing": "Executing emergency stop!",
        "estop.done": "🚨 Emergency stop sent.",
        # Settings
        "settings.title": "⚙ Settings",
        "settings.notifications": "Notifications",
        "settings.poll": "Poll interval",
        "settings.language": "Language",
        "settings.toggle_notif": "Toggle notifications",
        # Adjust
        "adjust.title": "🎛 Print Adjustments",
        "adjust.speed": "Speed: {val}%",
        "adjust.flow": "Flow: {val}%",
        "adjust.fan": "Fan: {val}%",
        "adjust.z_offset": "Z-offset: {val} mm",
        "adjust.z_up": "Z +{step}",
        "adjust.z_down": "Z -{step}",
        "adjust.z_reset": "Z Reset",
        "adjust.speed_set": "Speed → {val}%",
        "adjust.flow_set": "Flow → {val}%",
        "adjust.fan_set": "Fan → {val}%",
        "adjust.z_set": "Z-offset adjusted {val} mm",
        "adjust.z_reset_done": "Z-offset reset.",
        # Printers
        "printers.title": "🖨 Select Printer",
        "printers.switched": "✅ Switched to {name}",
        "printers.status_all": "📊 All Status",
        # History
        "history.title": "📜 Print History",
        "history.total": "jobs",
        # Bed mesh
        "bed_mesh.title": "🗺 Bed Mesh",
        "bed_mesh.no_data": "No bed mesh data available.",
        "bed_mesh.no_matrix": "Mesh profile found but no matrix data.",
    },
    "de": {
        "btn.back_menu": "⬅ Menü",
        "btn.back": "⬅ Zurück",
        "btn.refresh": "🔄 Aktualisieren",
        "btn.next": "▶ Weiter",
        "btn.prev": "◀ Zurück",
        "menu.welcome": "👋 Willkommen! Wähle eine Option:",
        "menu.title": "📋 Hauptmenü",
        "menu.status": "📊 Status",
        "menu.temps": "🌡 Temperaturen",
        "menu.files": "📁 Dateien",
        "menu.control": "🎮 Steuerung",
        "menu.gcode": "⌨ GCode",
        "menu.macros": "🔧 Makros",
        "menu.camera": "📷 Kamera",
        "menu.system": "💻 System",
        "menu.estop": "🚨 Notstopp",
        "menu.settings": "⚙ Einstellungen",
        "menu.adjust": "🎛 Anpassungen",
        "menu.history": "📜 Verlauf",
        "menu.bed_mesh": "🗺 Bettgitter",
        "menu.printers": "🖨 Drucker",
        "status.title": "📊 Druckerstatus",
        "status.offline": "❌ Drucker offline oder nicht erreichbar.",
        "status.file": "Datei",
        "status.state": "Zustand",
        "status.progress": "Fortschritt",
        "status.hotend": "Hotend",
        "status.bed": "Bett",
        "status.fan": "Lüfter",
        "status.speed": "Geschwindigkeit",
        "status.print_time": "Druckzeit",
        "status.total_time": "Gesamtzeit",
        "status.snapshot": "📷 Snapshot",
        "status.auto_on": "⏸ Auto-aus",
        "status.auto_off": "▶ Auto-an",
        "temps.title": "🌡 Temperatursteuerung",
        "temps.custom": "Benutzerdefiniert",
        "temps.cool_all": "❄ Alles kühlen",
        "temps.set_hotend": "Hotend → {val}°C",
        "temps.set_bed": "Bett → {val}°C",
        "temps.cooled": "Abkühlung läuft...",
        "temps.enter_hotend": "Hotend-Temperatur eingeben (°C):",
        "temps.enter_bed": "Bett-Temperatur eingeben (°C):",
        "files.title": "📁 Dateien",
        "files.files": "Dateien",
        "files.page": "Seite",
        "files.sort": "Sortieren",
        "files.size": "Größe",
        "files.filament": "Filament",
        "files.time": "Geschätzte Zeit",
        "files.layer": "Schichthöhe",
        "files.slicer": "Slicer",
        "files.print": "🖨 Drucken",
        "files.delete": "🗑 Löschen",
        "files.print_confirm": "{name} drucken?",
        "files.print_yes": "✅ Ja, drucken",
        "files.print_no": "❌ Abbrechen",
        "files.print_started": "✅ Druckt: {name}",
        "files.print_failed": "❌ Start fehlgeschlagen: {name}",
        "files.delete_confirm": "{name} löschen?",
        "files.delete_yes": "✅ Ja, löschen",
        "files.delete_no": "❌ Abbrechen",
        "files.deleted": "🗑 Gelöscht: {name}",
        "files.delete_failed": "❌ Löschen fehlgeschlagen: {name}",
        "control.title": "🎮 Drucksteuerung",
        "control.pause": "⏸ Pause",
        "control.resume": "▶ Fortsetzen",
        "control.cancel": "⏹ Abbrechen",
        "control.home": "🏠 Home",
        "control.motors_off": "💤 Motoren aus",
        "control.cancel_confirm": "⚠ Aktuellen Druck abbrechen?",
        "control.cancel_yes": "✅ Ja, abbrechen",
        "control.cancel_no": "❌ Nein",
        "control.paused": "Druck pausiert.",
        "control.resumed": "Druck fortgesetzt.",
        "control.cancelled": "Druck abgebrochen.",
        "control.homed": "Gehomed.",
        "control.motors_off_done": "Motoren aus.",
        "gcode.title": "⌨ GCode-Konsole\n\nBefehl senden oder Schnellknopf wählen:",
        "macros.title": "🔧 Makros",
        "macros.found": "gefunden",
        "macros.confirm": "Makro ausführen: {name}?",
        "macros.run_yes": "✅ Ausführen",
        "macros.run_no": "❌ Abbrechen",
        "macros.ran": "✅ Ausgeführt: {name}",
        "macros.failed": "❌ Fehlgeschlagen: {name}",
        "camera.title": "📷 Kamera",
        "camera.snapshot": "📸 Snapshot",
        "camera.stream": "📺 Live-Stream",
        "camera.fetching": "Snapshot wird abgerufen...",
        "camera.caption": "📸 Snapshot",
        "camera.error": "❌ Snapshot konnte nicht abgerufen werden.",
        "system.title": "💻 Systeminfo",
        "system.klipper": "Klipper",
        "system.moonraker": "Moonraker",
        "system.cpu": "CPU",
        "system.disk": "Festplatte",
        "system.cpu_usage": "CPU-Auslastung",
        "system.mem": "Speicher",
        "system.uptime": "Laufzeit",
        "system.fw_restart": "🔄 FW-Neustart",
        "system.host_restart": "🔌 Host-Neustart",
        "system.confirm": "⚠ Bestätigen: {action}?",
        "system.confirm_yes": "✅ Ja",
        "system.confirm_no": "❌ Nein",
        "system.fw_restarted": "✅ Firmware neu gestartet.",
        "system.host_restarted": "✅ Host-Neustart eingeleitet.",
        "estop.confirm": "🚨 NOTSTOPP — bist du sicher?",
        "estop.confirm_yes": "🚨 JA, STOPP",
        "estop.confirm_no": "❌ Abbrechen",
        "estop.executing": "Notstopp wird ausgeführt!",
        "estop.done": "🚨 Notstopp gesendet.",
        "settings.title": "⚙ Einstellungen",
        "settings.notifications": "Benachrichtigungen",
        "settings.poll": "Abfrageintervall",
        "settings.language": "Sprache",
        "settings.toggle_notif": "Benachrichtigungen umschalten",
        "adjust.title": "🎛 Druckanpassungen",
        "adjust.speed": "Geschwindigkeit: {val}%",
        "adjust.flow": "Fluss: {val}%",
        "adjust.fan": "Lüfter: {val}%",
        "adjust.z_offset": "Z-Offset: {val} mm",
        "adjust.z_up": "Z +{step}",
        "adjust.z_down": "Z -{step}",
        "adjust.z_reset": "Z Zurücksetzen",
        "adjust.speed_set": "Geschwindigkeit → {val}%",
        "adjust.flow_set": "Fluss → {val}%",
        "adjust.fan_set": "Lüfter → {val}%",
        "adjust.z_set": "Z-Offset angepasst {val} mm",
        "adjust.z_reset_done": "Z-Offset zurückgesetzt.",
        "printers.title": "🖨 Drucker auswählen",
        "printers.switched": "✅ Gewechselt zu {name}",
        "printers.status_all": "📊 Alle Status",
        "history.title": "📜 Druckverlauf",
        "history.total": "Aufträge",
        "bed_mesh.title": "🗺 Bettgitter",
        "bed_mesh.no_data": "Keine Bettgitterdaten verfügbar.",
        "bed_mesh.no_matrix": "Profil gefunden, aber keine Matrixdaten.",
    },
    "ru": {
        "btn.back_menu": "⬅ Меню",
        "btn.back": "⬅ Назад",
        "btn.refresh": "🔄 Обновить",
        "btn.next": "▶ Вперёд",
        "btn.prev": "◀ Назад",
        "menu.welcome": "👋 Добро пожаловать! Выберите опцию:",
        "menu.title": "📋 Главное меню",
        "menu.status": "📊 Статус",
        "menu.temps": "🌡 Температуры",
        "menu.files": "📁 Файлы",
        "menu.control": "🎮 Управление",
        "menu.gcode": "⌨ GCode",
        "menu.macros": "🔧 Макросы",
        "menu.camera": "📷 Камера",
        "menu.system": "💻 Система",
        "menu.estop": "🚨 Аварийная остановка",
        "menu.settings": "⚙ Настройки",
        "menu.adjust": "🎛 Регулировка",
        "menu.history": "📜 История",
        "menu.bed_mesh": "🗺 Сетка стола",
        "menu.printers": "🖨 Принтеры",
        "status.title": "📊 Статус принтера",
        "status.offline": "❌ Принтер недоступен.",
        "status.file": "Файл",
        "status.state": "Состояние",
        "status.progress": "Прогресс",
        "status.hotend": "Хотэнд",
        "status.bed": "Стол",
        "status.fan": "Вентилятор",
        "status.speed": "Скорость",
        "status.print_time": "Время печати",
        "status.total_time": "Общее время",
        "status.snapshot": "📷 Снимок",
        "status.auto_on": "⏸ Авто-выкл",
        "status.auto_off": "▶ Авто-вкл",
        "temps.title": "🌡 Управление температурой",
        "temps.custom": "Своя",
        "temps.cool_all": "❄ Охладить всё",
        "temps.set_hotend": "Хотэнд → {val}°C",
        "temps.set_bed": "Стол → {val}°C",
        "temps.cooled": "Охлаждение...",
        "temps.enter_hotend": "Введите температуру хотэнда (°C):",
        "temps.enter_bed": "Введите температуру стола (°C):",
        "files.title": "📁 Файлы",
        "files.files": "файлов",
        "files.page": "стр.",
        "files.sort": "Сортировка",
        "files.size": "Размер",
        "files.filament": "Филамент",
        "files.time": "Расч. время",
        "files.layer": "Высота слоя",
        "files.slicer": "Слайсер",
        "files.print": "🖨 Печать",
        "files.delete": "🗑 Удалить",
        "files.print_confirm": "Печатать {name}?",
        "files.print_yes": "✅ Да, печатать",
        "files.print_no": "❌ Отмена",
        "files.print_started": "✅ Печать: {name}",
        "files.print_failed": "❌ Ошибка запуска: {name}",
        "files.delete_confirm": "Удалить {name}?",
        "files.delete_yes": "✅ Да, удалить",
        "files.delete_no": "❌ Отмена",
        "files.deleted": "🗑 Удалено: {name}",
        "files.delete_failed": "❌ Ошибка удаления: {name}",
        "control.title": "🎮 Управление печатью",
        "control.pause": "⏸ Пауза",
        "control.resume": "▶ Продолжить",
        "control.cancel": "⏹ Отменить",
        "control.home": "🏠 Home",
        "control.motors_off": "💤 Моторы выкл",
        "control.cancel_confirm": "⚠ Отменить текущую печать?",
        "control.cancel_yes": "✅ Да, отменить",
        "control.cancel_no": "❌ Нет",
        "control.paused": "Печать на паузе.",
        "control.resumed": "Печать продолжена.",
        "control.cancelled": "Печать отменена.",
        "control.homed": "Домашняя позиция.",
        "control.motors_off_done": "Моторы выключены.",
        "gcode.title": "⌨ GCode-консоль\n\nОтправьте команду или выберите кнопку:",
        "macros.title": "🔧 Макросы",
        "macros.found": "найдено",
        "macros.confirm": "Запустить макрос: {name}?",
        "macros.run_yes": "✅ Запустить",
        "macros.run_no": "❌ Отмена",
        "macros.ran": "✅ Выполнено: {name}",
        "macros.failed": "❌ Ошибка: {name}",
        "camera.title": "📷 Камера",
        "camera.snapshot": "📸 Снимок",
        "camera.stream": "📺 Трансляция",
        "camera.fetching": "Получение снимка...",
        "camera.caption": "📸 Снимок",
        "camera.error": "❌ Не удалось получить снимок.",
        "system.title": "💻 Система",
        "system.klipper": "Klipper",
        "system.moonraker": "Moonraker",
        "system.cpu": "Процессор",
        "system.disk": "Диск",
        "system.cpu_usage": "Нагрузка CPU",
        "system.mem": "Память",
        "system.uptime": "Аптайм",
        "system.fw_restart": "🔄 Рестарт прошивки",
        "system.host_restart": "🔌 Рестарт хоста",
        "system.confirm": "⚠ Подтвердить: {action}?",
        "system.confirm_yes": "✅ Да",
        "system.confirm_no": "❌ Нет",
        "system.fw_restarted": "✅ Прошивка перезапущена.",
        "system.host_restarted": "✅ Рестарт хоста начат.",
        "estop.confirm": "🚨 АВАРИЙНАЯ ОСТАНОВКА — вы уверены?",
        "estop.confirm_yes": "🚨 ДА, СТОП",
        "estop.confirm_no": "❌ Отмена",
        "estop.executing": "Выполняется аварийная остановка!",
        "estop.done": "🚨 Аварийная остановка отправлена.",
        "settings.title": "⚙ Настройки",
        "settings.notifications": "Уведомления",
        "settings.poll": "Интервал опроса",
        "settings.language": "Язык",
        "settings.toggle_notif": "Переключить уведомления",
        "adjust.title": "🎛 Регулировка печати",
        "adjust.speed": "Скорость: {val}%",
        "adjust.flow": "Поток: {val}%",
        "adjust.fan": "Вентилятор: {val}%",
        "adjust.z_offset": "Z-смещение: {val} мм",
        "adjust.z_up": "Z +{step}",
        "adjust.z_down": "Z -{step}",
        "adjust.z_reset": "Сбросить Z",
        "adjust.speed_set": "Скорость → {val}%",
        "adjust.flow_set": "Поток → {val}%",
        "adjust.fan_set": "Вентилятор → {val}%",
        "adjust.z_set": "Z-смещение изменено на {val} мм",
        "adjust.z_reset_done": "Z-смещение сброшено.",
        "printers.title": "🖨 Выбор принтера",
        "printers.switched": "✅ Переключено на {name}",
        "printers.status_all": "📊 Все статусы",
        "history.title": "📜 История печати",
        "history.total": "заданий",
        "bed_mesh.title": "🗺 Сетка стола",
        "bed_mesh.no_data": "Нет данных сетки стола.",
        "bed_mesh.no_matrix": "Профиль найден, но нет данных матрицы.",
    },
    "pl": {
        "btn.back_menu": "⬅ Menu",
        "btn.back": "⬅ Wstecz",
        "btn.refresh": "🔄 Odśwież",
        "btn.next": "▶ Dalej",
        "btn.prev": "◀ Wstecz",
        "menu.welcome": "👋 Witaj! Wybierz opcję:",
        "menu.title": "📋 Menu główne",
        "menu.status": "📊 Status",
        "menu.temps": "🌡 Temperatury",
        "menu.files": "📁 Pliki",
        "menu.control": "🎮 Sterowanie",
        "menu.gcode": "⌨ GCode",
        "menu.macros": "🔧 Makra",
        "menu.camera": "📷 Kamera",
        "menu.system": "💻 System",
        "menu.estop": "🚨 Awaryjne stop",
        "menu.settings": "⚙ Ustawienia",
        "menu.adjust": "🎛 Korekty",
        "menu.history": "📜 Historia",
        "menu.bed_mesh": "🗺 Siatka stołu",
        "menu.printers": "🖨 Drukarki",
        "status.title": "📊 Status drukarki",
        "status.offline": "❌ Drukarka offline lub niedostępna.",
        "status.file": "Plik",
        "status.state": "Stan",
        "status.progress": "Postęp",
        "status.hotend": "Hotend",
        "status.bed": "Stół",
        "status.fan": "Wentylator",
        "status.speed": "Prędkość",
        "status.print_time": "Czas druku",
        "status.total_time": "Łączny czas",
        "status.snapshot": "📷 Zdjęcie",
        "status.auto_on": "⏸ Auto-wył",
        "status.auto_off": "▶ Auto-wł",
        "temps.title": "🌡 Sterowanie temperaturą",
        "temps.custom": "Własna",
        "temps.cool_all": "❄ Chłodź wszystko",
        "temps.set_hotend": "Hotend → {val}°C",
        "temps.set_bed": "Stół → {val}°C",
        "temps.cooled": "Chłodzenie...",
        "temps.enter_hotend": "Podaj temperaturę hotend (°C):",
        "temps.enter_bed": "Podaj temperaturę stołu (°C):",
        "files.title": "📁 Pliki",
        "files.files": "plików",
        "files.page": "str.",
        "files.sort": "Sortuj",
        "files.size": "Rozmiar",
        "files.filament": "Filament",
        "files.time": "Szac. czas",
        "files.layer": "Wysokość warstwy",
        "files.slicer": "Slicer",
        "files.print": "🖨 Drukuj",
        "files.delete": "🗑 Usuń",
        "files.print_confirm": "Drukować {name}?",
        "files.print_yes": "✅ Tak, drukuj",
        "files.print_no": "❌ Anuluj",
        "files.print_started": "✅ Drukowanie: {name}",
        "files.print_failed": "❌ Błąd startu: {name}",
        "files.delete_confirm": "Usunąć {name}?",
        "files.delete_yes": "✅ Tak, usuń",
        "files.delete_no": "❌ Anuluj",
        "files.deleted": "🗑 Usunięto: {name}",
        "files.delete_failed": "❌ Błąd usuwania: {name}",
        "control.title": "🎮 Sterowanie drukiem",
        "control.pause": "⏸ Pauza",
        "control.resume": "▶ Wznów",
        "control.cancel": "⏹ Anuluj",
        "control.home": "🏠 Home",
        "control.motors_off": "💤 Silniki wył",
        "control.cancel_confirm": "⚠ Anulować bieżący druk?",
        "control.cancel_yes": "✅ Tak, anuluj",
        "control.cancel_no": "❌ Nie",
        "control.paused": "Druk wstrzymany.",
        "control.resumed": "Druk wznowiony.",
        "control.cancelled": "Druk anulowany.",
        "control.homed": "Pozycja domowa.",
        "control.motors_off_done": "Silniki wyłączone.",
        "gcode.title": "⌨ Konsola GCode\n\nWyślij komendę lub wybierz przycisk:",
        "macros.title": "🔧 Makra",
        "macros.found": "znaleziono",
        "macros.confirm": "Uruchomić makro: {name}?",
        "macros.run_yes": "✅ Uruchom",
        "macros.run_no": "❌ Anuluj",
        "macros.ran": "✅ Uruchomiono: {name}",
        "macros.failed": "❌ Błąd: {name}",
        "camera.title": "📷 Kamera",
        "camera.snapshot": "📸 Zdjęcie",
        "camera.stream": "📺 Stream na żywo",
        "camera.fetching": "Pobieranie zdjęcia...",
        "camera.caption": "📸 Zdjęcie",
        "camera.error": "❌ Nie udało się pobrać zdjęcia.",
        "system.title": "💻 Informacje o systemie",
        "system.klipper": "Klipper",
        "system.moonraker": "Moonraker",
        "system.cpu": "CPU",
        "system.disk": "Dysk",
        "system.cpu_usage": "Użycie CPU",
        "system.mem": "Pamięć",
        "system.uptime": "Czas pracy",
        "system.fw_restart": "🔄 Restart FW",
        "system.host_restart": "🔌 Restart hosta",
        "system.confirm": "⚠ Potwierdź: {action}?",
        "system.confirm_yes": "✅ Tak",
        "system.confirm_no": "❌ Nie",
        "system.fw_restarted": "✅ Firmware zrestartowany.",
        "system.host_restarted": "✅ Restart hosta zainicjowany.",
        "estop.confirm": "🚨 AWARYJNE STOP — na pewno?",
        "estop.confirm_yes": "🚨 TAK, STOP",
        "estop.confirm_no": "❌ Anuluj",
        "estop.executing": "Wykonuję awaryjne stop!",
        "estop.done": "🚨 Awaryjne stop wysłane.",
        "settings.title": "⚙ Ustawienia",
        "settings.notifications": "Powiadomienia",
        "settings.poll": "Interwał odpytywania",
        "settings.language": "Język",
        "settings.toggle_notif": "Przełącz powiadomienia",
        "adjust.title": "🎛 Korekty druku",
        "adjust.speed": "Prędkość: {val}%",
        "adjust.flow": "Przepływ: {val}%",
        "adjust.fan": "Wentylator: {val}%",
        "adjust.z_offset": "Z-offset: {val} mm",
        "adjust.z_up": "Z +{step}",
        "adjust.z_down": "Z -{step}",
        "adjust.z_reset": "Resetuj Z",
        "adjust.speed_set": "Prędkość → {val}%",
        "adjust.flow_set": "Przepływ → {val}%",
        "adjust.fan_set": "Wentylator → {val}%",
        "adjust.z_set": "Z-offset zmieniony o {val} mm",
        "adjust.z_reset_done": "Z-offset zresetowany.",
        "printers.title": "🖨 Wybór drukarki",
        "printers.switched": "✅ Przełączono na {name}",
        "printers.status_all": "📊 Wszystkie statusy",
        "history.title": "📜 Historia druku",
        "history.total": "zadań",
        "bed_mesh.title": "🗺 Siatka stołu",
        "bed_mesh.no_data": "Brak danych siatki stołu.",
        "bed_mesh.no_matrix": "Znaleziono profil, ale brak danych macierzy.",
    },
}


def t(key: str, lang: str = "en") -> str:
    """Translate a key. Falls back to English if not found."""
    return STRINGS.get(lang, STRINGS["en"]).get(key) or STRINGS["en"].get(key, key)
